package View;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Model.ManageSpareParts;

//@author Aaroophan

public class ManageSparePartsUI extends javax.swing.JFrame {

    /**
     * Creates new form ManageSparePartsUI
     */
    public ManageSparePartsUI() {
        initComponents();
    }
    String SparePartName;
    String SparePartID;
    int Total = 0;
    int Btn=0;
    String[] SPNameArr = {"Bezel", "Case", "Crown", "Crystle", "Dial", "Hand", "HourMarker"};

    DefaultTableModel ModelTable;
    ManageSpareParts MSP = new ManageSpareParts();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SPNBezel = new javax.swing.JRadioButton();
        SPNCase = new javax.swing.JRadioButton();
        SPNCrown = new javax.swing.JRadioButton();
        SPNCrystle = new javax.swing.JRadioButton();
        SPNDial = new javax.swing.JRadioButton();
        SPNHand = new javax.swing.JRadioButton();
        SPNHourMarker = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtSPQuantity = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        avbBezel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        avbCase = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        avbCrystle = new javax.swing.JLabel();
        avbCrown = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        avbDial = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        avbHand = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        avbHourMarker = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSPOoStock = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        jPanel3.setBackground(new java.awt.Color(44, 47, 51));

        jPanel1.setBackground(new java.awt.Color(44, 47, 51));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(223, 223, 223));
        jLabel5.setText("Spare Part Name");

        SPNBezel.setBackground(new java.awt.Color(44, 47, 51));
        SPNBezel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SPNBezel.setForeground(new java.awt.Color(223, 223, 223));
        SPNBezel.setText("Bezel");
        SPNBezel.setOpaque(false);
        SPNBezel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPNBezelActionPerformed(evt);
            }
        });

        SPNCase.setBackground(new java.awt.Color(44, 47, 51));
        SPNCase.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SPNCase.setForeground(new java.awt.Color(223, 223, 223));
        SPNCase.setText("Case");
        SPNCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPNCaseActionPerformed(evt);
            }
        });

        SPNCrown.setBackground(new java.awt.Color(44, 47, 51));
        SPNCrown.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SPNCrown.setForeground(new java.awt.Color(223, 223, 223));
        SPNCrown.setText("Crown");
        SPNCrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPNCrownActionPerformed(evt);
            }
        });

        SPNCrystle.setBackground(new java.awt.Color(44, 47, 51));
        SPNCrystle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SPNCrystle.setForeground(new java.awt.Color(223, 223, 223));
        SPNCrystle.setText("Crystle");
        SPNCrystle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPNCrystleActionPerformed(evt);
            }
        });

        SPNDial.setBackground(new java.awt.Color(44, 47, 51));
        SPNDial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SPNDial.setForeground(new java.awt.Color(223, 223, 223));
        SPNDial.setText("Dial");
        SPNDial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPNDialActionPerformed(evt);
            }
        });

        SPNHand.setBackground(new java.awt.Color(44, 47, 51));
        SPNHand.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SPNHand.setForeground(new java.awt.Color(223, 223, 223));
        SPNHand.setText("Hand");
        SPNHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPNHandActionPerformed(evt);
            }
        });

        SPNHourMarker.setBackground(new java.awt.Color(44, 47, 51));
        SPNHourMarker.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SPNHourMarker.setForeground(new java.awt.Color(223, 223, 223));
        SPNHourMarker.setText("Hour Marker");
        SPNHourMarker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPNHourMarkerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(223, 223, 223));
        jLabel2.setText("Quantity ");

        txtSPQuantity.setBackground(new java.awt.Color(25, 0, 50));
        txtSPQuantity.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtSPQuantity.setForeground(new java.awt.Color(223, 223, 223));
        txtSPQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnAdd.setBackground(new java.awt.Color(35, 39, 42));
        btnAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(223, 223, 223));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(35, 39, 42));
        btnRemove.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(223, 223, 223));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtSPQuantity))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SPNHand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SPNBezel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SPNDial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SPNCase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SPNCrown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SPNCrystle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SPNHourMarker, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(SPNBezel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPNCase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPNCrown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPNCrystle)
                .addGap(3, 3, 3)
                .addComponent(SPNDial)
                .addGap(3, 3, 3)
                .addComponent(SPNHand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPNHourMarker)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSPQuantity))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(44, 47, 51));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(223, 223, 223));
        jLabel6.setText("Availability");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 223, 223));
        jLabel3.setText("Bezel");

        avbBezel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avbBezel.setForeground(new java.awt.Color(223, 223, 223));
        avbBezel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avbBezel.setText("0");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(223, 223, 223));
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(223, 223, 223));
        jLabel8.setText("Case");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(223, 223, 223));
        jLabel9.setText("-");

        avbCase.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avbCase.setForeground(new java.awt.Color(223, 223, 223));
        avbCase.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avbCase.setText("0");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(223, 223, 223));
        jLabel11.setText("Crown");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(223, 223, 223));
        jLabel12.setText("-");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(223, 223, 223));
        jLabel13.setText("Crystle");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(223, 223, 223));
        jLabel14.setText("-");

        avbCrystle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avbCrystle.setForeground(new java.awt.Color(223, 223, 223));
        avbCrystle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avbCrystle.setText("0");

        avbCrown.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avbCrown.setForeground(new java.awt.Color(223, 223, 223));
        avbCrown.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avbCrown.setText("0");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(223, 223, 223));
        jLabel17.setText("-");

        avbDial.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avbDial.setForeground(new java.awt.Color(223, 223, 223));
        avbDial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avbDial.setText("0");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(223, 223, 223));
        jLabel19.setText("Dial");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(223, 223, 223));
        jLabel20.setText("-");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(223, 223, 223));
        jLabel21.setText("Hand");

        avbHand.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avbHand.setForeground(new java.awt.Color(223, 223, 223));
        avbHand.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avbHand.setText("0");

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(223, 223, 223));
        jLabel23.setText("-");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(223, 223, 223));
        jLabel24.setText("Hour Marker");

        avbHourMarker.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avbHourMarker.setForeground(new java.awt.Color(223, 223, 223));
        avbHourMarker.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avbHourMarker.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avbCase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(avbCrown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avbCrystle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avbDial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avbHand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avbHourMarker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avbBezel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(avbBezel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(avbCase, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(avbCrown, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(avbCrystle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(avbDial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(avbHand, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(avbHourMarker, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(25, 0, 50));

        jTable1.setBackground(new java.awt.Color(25, 0, 50));
        jTable1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(223, 223, 223));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(223, 223, 223));
        jTable1.setOpaque(false);
        jTable1.setSelectionForeground(new java.awt.Color(25, 0, 50));
        jScrollPane2.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSPOoStock.setBackground(new java.awt.Color(35, 39, 42));
        btnSPOoStock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSPOoStock.setForeground(new java.awt.Color(223, 223, 223));
        btnSPOoStock.setText("Spare Parts Out-of-Stock");
        btnSPOoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPOoStockActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(25, 0, 50));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Spare Parts");

        btnGoBack.setBackground(new java.awt.Color(35, 39, 42));
        btnGoBack.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(223, 223, 223));
        btnGoBack.setText("Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGoBack)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21))
        );

        btnDelete.setBackground(new java.awt.Color(35, 39, 42));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(223, 223, 223));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnDelete)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSPOoStock)
                        .addGap(53, 53, 53))))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSPOoStock))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        IfNotEmpty();

        if ((SPNBezel.isSelected() == false) && (SPNCase.isSelected() == false) && (SPNCrown.isSelected() == false) 
                && (SPNCrystle.isSelected() == false) && (SPNDial.isSelected() == false) && (SPNHand.isSelected() == false) 
                && (SPNHourMarker.isSelected() == false)) {
            JOptionPane.showMessageDialog(this, "Please Select A Spare Part", "Spare Parts Management", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            Total = MSP.AddAction(SparePartName, GetSPQuantity());
            ModelTable = (DefaultTableModel) jTable1.getModel();
            ModelTable.addRow(new Object[]{
                SparePartName,
                SparePartID,
                txtSPQuantity.getText(),
                Total,});
            
            AvbSetText();
            Clear();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int RemovedQuantity = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        Total = MSP.RemoveAction(SparePartName, RemovedQuantity);
        if (Total < 0) {
            JOptionPane.showMessageDialog(this, SparePartName + " Out-of-Stock", "Spare Parts Management", JOptionPane.ERROR_MESSAGE);
        } else {
            ModelTable.addRow(new Object[]{
                SparePartName,
                SparePartID,
                "(Deleted) " + RemovedQuantity,
                Total,});

            ModelTable.removeRow(jTable1.getSelectedRow());

            AvbSetText();
            Clear();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        IfNotEmpty();

        if ((SPNBezel.isSelected() == false) && (SPNCase.isSelected() == false) && (SPNCrown.isSelected() == false) 
                && (SPNCrystle.isSelected() == false) && (SPNDial.isSelected() == false) && (SPNHand.isSelected() == false) 
                && (SPNHourMarker.isSelected() == false)) {
            JOptionPane.showMessageDialog(this, "Please Select A Spare Part");
        } else {

            Total = MSP.RemoveAction(SparePartName, GetSPQuantity());
            if (Total < 0) {
                JOptionPane.showMessageDialog(this, SparePartName + " Out-of-Stock", "Spare Parts Management", JOptionPane.ERROR_MESSAGE);
            } else {
                ModelTable = (DefaultTableModel) jTable1.getModel();
                ModelTable.addRow(new Object[]{
                    SparePartName,
                    SparePartID,
                    "-" + txtSPQuantity.getText(),
                    Total,});

                AvbSetText();
                Clear();
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSPOoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPOoStockActionPerformed

        //SHANGGAVI
        SparePartsOutofStockUI SPOoSUI = new SparePartsOutofStockUI();
        SPOoSUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSPOoStockActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        //BACK TO MAIN UI
        PaperClipsMainUI MainUI = new PaperClipsMainUI();
        MainUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void SPNBezelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPNBezelActionPerformed
        Btn=1;
        BtnGroup();
    }//GEN-LAST:event_SPNBezelActionPerformed

    private void SPNCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPNCaseActionPerformed
        Btn=2;
        BtnGroup();
    }//GEN-LAST:event_SPNCaseActionPerformed

    private void SPNCrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPNCrownActionPerformed
        Btn=3;
        BtnGroup();
    }//GEN-LAST:event_SPNCrownActionPerformed

    private void SPNHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPNHandActionPerformed
        Btn=6;
        BtnGroup();
    }//GEN-LAST:event_SPNHandActionPerformed

    private void SPNCrystleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPNCrystleActionPerformed
        Btn=4;
        BtnGroup();
    }//GEN-LAST:event_SPNCrystleActionPerformed

    private void SPNDialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPNDialActionPerformed
        Btn=5;
        BtnGroup();
    }//GEN-LAST:event_SPNDialActionPerformed

    private void SPNHourMarkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPNHourMarkerActionPerformed
        Btn=7;
        BtnGroup();
    }//GEN-LAST:event_SPNHourMarkerActionPerformed

    
    public void BtnGroup()
    {
        SPNBezel.setSelected(false);
        SPNCase.setSelected(false);
        SPNCrown.setSelected(false);
        SPNCrystle.setSelected(false);
        SPNDial.setSelected(false);
        SPNHand.setSelected(false);
        SPNHourMarker.setSelected(false);
        
        switch(Btn){
            case 1: SPNBezel.setSelected(true); break;
            case 2: SPNCase.setSelected(true); break;
            case 3: SPNCrown.setSelected(true); break;
            case 4: SPNCrystle.setSelected(true); break;
            case 5: SPNDial.setSelected(true); break;
            case 6: SPNHand.setSelected(true); break;
            case 7: SPNHourMarker.setSelected(true); break;
        }
    }
    
    public String IfNotEmpty() {
        if (txtSPQuantity.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill The Quantity", "Spare Parts Management", JOptionPane.INFORMATION_MESSAGE);
        } else {
            SparePartName = ButtonSelected();
            SparePartID = GiveID(SparePartName);
        }
        return null;
    }

    public int GetSPQuantity() {
        int SPQuantity = Integer.parseInt(txtSPQuantity.getText());
        return SPQuantity;
    }

    public String AvbSetText() {
        avbBezel.setText(Integer.toString(ManageSpareParts.TotalArr[0]));
        avbCase.setText(Integer.toString(ManageSpareParts.TotalArr[1]));
        avbCrown.setText(Integer.toString(ManageSpareParts.TotalArr[2]));
        avbCrystle.setText(Integer.toString(ManageSpareParts.TotalArr[3]));
        avbDial.setText(Integer.toString(ManageSpareParts.TotalArr[4]));
        avbHand.setText(Integer.toString(ManageSpareParts.TotalArr[5]));
        avbHourMarker.setText(Integer.toString(ManageSpareParts.TotalArr[6]));
        return null;
    }

    //Button SelectionHere
    public String ButtonSelected() {
        if (SPNBezel.isSelected() == true) {
            return "Bezel";
        } else if (SPNCase.isSelected() == true) {
            return "Case";
        } else if (SPNCrown.isSelected() == true) {
            return "Crown";
        } else if (SPNCrystle.isSelected() == true) {
            return "Crystle";
        } else if (SPNDial.isSelected() == true) {
            return "Dial";
        } else if (SPNHand.isSelected() == true) {
            return "Hand";
        } else if (SPNHourMarker.isSelected() == true) {
            return "Hour Marker";
        } else {
            return "INVALID";
        }
    }
    
    public String GiveID(String SparePartName) {
        if (SparePartName.equals("Bezel")) {
            return "SP001";
        } else if (SparePartName.equals("Case")) {
            return "SP002";
        } else if (SparePartName.equals("Crown")) {
            return "SP003";
        } else if (SparePartName.equals("Crystle")) {
            return "SP004";
        } else if (SparePartName.equals("Dial")) {
            return "SP005";
        } else if (SparePartName.equals("Hand")) {
            return "SP006";
        } else if (SparePartName.equals("Hour Marker")) {
            return "SP007";
        } else {
            return "INVALID";
        }
    }
    
    private void Clear() {
        txtSPQuantity.setText("");
        SPNBezel.setSelected(false);
        SPNCase.setSelected(false);
        SPNCrown.setSelected(false);
        SPNCrystle.setSelected(false);
        SPNDial.setSelected(false);
        SPNHand.setSelected(false);
        SPNHourMarker.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSparePartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSparePartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSparePartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSparePartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSparePartsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SPNBezel;
    private javax.swing.JRadioButton SPNCase;
    private javax.swing.JRadioButton SPNCrown;
    private javax.swing.JRadioButton SPNCrystle;
    private javax.swing.JRadioButton SPNDial;
    private javax.swing.JRadioButton SPNHand;
    private javax.swing.JRadioButton SPNHourMarker;
    private javax.swing.JLabel avbBezel;
    private javax.swing.JLabel avbCase;
    private javax.swing.JLabel avbCrown;
    private javax.swing.JLabel avbCrystle;
    private javax.swing.JLabel avbDial;
    private javax.swing.JLabel avbHand;
    private javax.swing.JLabel avbHourMarker;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSPOoStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSPQuantity;
    // End of variables declaration//GEN-END:variables
}
