package View;

//@author Aaroophan

public class PaperClipsMainUI extends javax.swing.JFrame {

    /**
     * Creates new form PaperClipsMainUI
     */
    public PaperClipsMainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSalesInvoicesManagement = new javax.swing.JButton();
        btnRepairJobsManagement = new javax.swing.JButton();
        btnSparePartsManagement = new javax.swing.JButton();
        btnSparePartsSuppliersManagement = new javax.swing.JButton();
        btnMonthlyReport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 47, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(540, 442));
        jPanel1.setMinimumSize(new java.awt.Dimension(540, 442));
        jPanel1.setName(""); // NOI18N

        jPanel2.setBackground(new java.awt.Color(44, 47, 51));

        btnSalesInvoicesManagement.setBackground(new java.awt.Color(35, 39, 42));
        btnSalesInvoicesManagement.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSalesInvoicesManagement.setForeground(new java.awt.Color(246, 246, 246));
        btnSalesInvoicesManagement.setText("Sales Invoices Management");
        btnSalesInvoicesManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesInvoicesManagementActionPerformed(evt);
            }
        });

        btnRepairJobsManagement.setBackground(new java.awt.Color(35, 39, 42));
        btnRepairJobsManagement.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRepairJobsManagement.setForeground(new java.awt.Color(246, 246, 246));
        btnRepairJobsManagement.setText("Repair Jobs Management");
        btnRepairJobsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairJobsManagementActionPerformed(evt);
            }
        });

        btnSparePartsManagement.setBackground(new java.awt.Color(35, 39, 42));
        btnSparePartsManagement.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSparePartsManagement.setForeground(new java.awt.Color(246, 246, 246));
        btnSparePartsManagement.setText("Spare Parts Management");
        btnSparePartsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparePartsManagementActionPerformed(evt);
            }
        });

        btnSparePartsSuppliersManagement.setBackground(new java.awt.Color(35, 39, 42));
        btnSparePartsSuppliersManagement.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSparePartsSuppliersManagement.setForeground(new java.awt.Color(246, 246, 246));
        btnSparePartsSuppliersManagement.setText("Spare Parts Suppliers Management");
        btnSparePartsSuppliersManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparePartsSuppliersManagementActionPerformed(evt);
            }
        });

        btnMonthlyReport.setBackground(new java.awt.Color(35, 39, 42));
        btnMonthlyReport.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMonthlyReport.setForeground(new java.awt.Color(246, 246, 246));
        btnMonthlyReport.setText("Monthly Income & Expenses Report");
        btnMonthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalesInvoicesManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRepairJobsManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSparePartsManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSparePartsSuppliersManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMonthlyReport, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnSalesInvoicesManagement)
                .addGap(24, 24, 24)
                .addComponent(btnRepairJobsManagement)
                .addGap(24, 24, 24)
                .addComponent(btnSparePartsManagement)
                .addGap(24, 24, 24)
                .addComponent(btnSparePartsSuppliersManagement)
                .addGap(24, 24, 24)
                .addComponent(btnMonthlyReport)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(25, 0, 50));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIMETICKER WATCH SHOP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        btnLogout.setBackground(new java.awt.Color(35, 39, 42));
        btnLogout.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(246, 246, 246));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalesInvoicesManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesInvoicesManagementActionPerformed
        TimeTickerWatchSalesManagementSystemUI WSM = new TimeTickerWatchSalesManagementSystemUI();
        WSM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalesInvoicesManagementActionPerformed

    private void btnRepairJobsManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairJobsManagementActionPerformed
        ManageRepairJobsUI MRJUI = new ManageRepairJobsUI();
        MRJUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRepairJobsManagementActionPerformed

    private void btnSparePartsManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparePartsManagementActionPerformed
        ManageSparePartsUI MSPUI = new ManageSparePartsUI();
        MSPUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSparePartsManagementActionPerformed

    private void btnSparePartsSuppliersManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparePartsSuppliersManagementActionPerformed
        SupplierManagementUI SMUI = new SupplierManagementUI();
        SMUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSparePartsSuppliersManagementActionPerformed

    private void btnMonthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyReportActionPerformed
        MonthlyIncomeExpenseReportUI MRUI = new MonthlyIncomeExpenseReportUI();
        MRUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMonthlyReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        TTLoginUI LO = new TTLoginUI();
        LO.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaperClipsMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaperClipsMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaperClipsMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaperClipsMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaperClipsMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMonthlyReport;
    private javax.swing.JButton btnRepairJobsManagement;
    private javax.swing.JButton btnSalesInvoicesManagement;
    private javax.swing.JButton btnSparePartsManagement;
    private javax.swing.JButton btnSparePartsSuppliersManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
